version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Giraf
      - POSTGRES_PASSWORD=Giraf123
      - POSTGRES_DB=giraf
      - PG_REP_USER=Rep
      - PG_REP_PASSWORD=Rep123
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pg_cluster
  pg_slave:
    build: ./slave
    environment:
      - POSTGRES_USER=Giraf
      - POSTGRES_PASSWORD=Giraf123
      - POSTGRES_DB=giraf
      - PG_REP_USER=Rep
      - PG_REP_PASSWORD=Rep123
      - PG_MASTER_HOST=pg_master
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data:
